default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "rails-ralix-tailwind_development")  %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "rails-ralix-tailwind_test")  %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "rails-ralix-tailwind_production")  %>
